# Generated by Django 2.2.14 on 2020-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.TextField(max_length=30, unique=True)),
                ('system_number', models.TextField(blank=True, max_length=30)),
                ('operation_number', models.TextField(max_length=30)),
                ('operation_name', models.TextField(max_length=30)),
                ('hmdescription', models.TextField(blank=True, max_length=300)),
                ('fix_action', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.TextField(max_length=30)),
            ],
        ),
    ]
